@echo off
start content\startghostbusters.bat
start content\youve-been-hacked.mp3
start content\naruto-fortnite-dance-u50cbuct1capy56m.gif
start content\tenor.gif
start content\hak.bat
start content\giphy(3).gif
start content\hak2.bat
start content\hak3.bat
start content\funnyhack.gif
start content\hak.bat
start content\hak2.bat
start content\hack-gif-12.gif
start content\hak3.bat
start content\giphy(2).gif
start content\hak.bat
start content\hak2.bat
start content\hak3.bat
start content\giphy(1).gif
start content\hak.bat
start content\hak2.bat
start content\hak3.bat
start content\hakk.gif
start content\hak.bat
start content\hak2.bat
start content\hak3.bat
start content\hacked-hack.gif
start content\naruto-fortnite-dance-u50cbuct1capy56m.gif
start content\cersei-laughing.gif


